---
name: Sys-Path
version: 0.03
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: get/configure system paths
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  IO::Any: 0
requires:
  File::Spec: 0
  IO::Any: 0
  List::MoreUtils: 0
build_requires:
  Test::More: 0
provides:
  Module::Build::SysPath:
    file: lib/Module/Build/SysPath.pm
    version: 0.01
  Sys::Path:
    file: lib/Sys/Path.pm
    version: 0.03
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
