---
name: Sys-Path
version: 0.07
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: get/configure system paths
license: perl
resources:
  bugtracker: http://github.com/jozef/Sys-Path/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/Sys-Path.git
build_requires:
  Test::More: 0
requires:
  File::Spec: 0
  List::MoreUtils: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Module::Build::SysPath:
    file: lib/Module/Build/SysPath.pm
    version: 0.07
  Sys::Path:
    file: lib/Sys/Path.pm
    version: 0.07
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - system
  - paths
  - instalation
  - deployment
  - applications
