---
name: Sys-Path
version: 0.09
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: supply autoconf style installation directories
license: perl
resources:
  bugtracker: http://github.com/jozef/Sys-Path/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/Sys-Path.git
build_requires:
  Test::Compile: 0.08
  Test::More: 0
requires:
  Digest::MD5: 0
  File::Spec: 0
  JSON::Util: 0
  List::MoreUtils: 0
  Text::Diff: 0
configure_requires:
  Module::Build: 0.35
provides:
  Sys::Path:
    file: lib/Sys/Path.pm
    version: 0.09
  Sys::Path::SPc:
    file: lib/Sys/Path/SPc.pm
    version: 0.09
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - system
  - paths
  - instalation
  - deployment
  - applications
